# Generated by Django 5.0.1 on 2024-01-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('date_published', models.DateField()),
                ('url', models.URLField()),
            ],
        ),
    ]
