# Generated by Django 5.0.1 on 2024-01-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='date_published',
            field=models.DateField(blank=True, null=True),
        ),
    ]
